### ISSUE TITLE
Adding switch to upper/lower case feature

### ISSUE THREAD

**Issue by tszyaul6** [LGUG2Z/helix-vim#9]
One very common feature I use in Neovim is to switching cases by `v-U` and `v-u`
As tested, the following configs work.

```toml
[keys.select]
# ... other configs
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
```

I wish helix supports chaining too... It's real good if we can use `f`, `t`, `F`, `T` without selection (but I don't think it's possible so far).

P.S. Thank you so much for making this wonderful config! I was doing the same thing, and soon found out that you have gone through all these, saving me hours! What you wrote in the readme also made me laugh so hard, you made my day!
